<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projet Data Visualisation</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f9f9f9;
            color: #333;
        }
        h1 {
            text-align: center;
            font-size: 3rem;
            color: #2c3e50;
            margin-bottom: 10px;
        }
        h2 {
            text-align: center;
            font-size: 2rem;
            color: #2980b9;
        }
        p {
            text-align: center;
            font-size: 1.2rem;
            margin: 10px auto;
            line-height: 1.6;
            color: black;
        }
        .container {
            width: 80%;
            margin: 50px auto;
            padding: 20px;
            background-color: #ffffff;
            border: 1px solid #dcdcdc;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .highlight {
            font-weight: bold;
            color: #e74c3c;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Projet Data Visualisation</h1>
        <h2>Cyril Kfouri, Mathias Robert, Maxime Maeder, Luc Renaud, Maxime Lambert</h2>
        <p><span class="highlight">Group 2 - Data and AI</span></p>
        <h2>Données Foncières</h2>
        <p><strong>Objectif:</strong> Solution pour un investisseur immobilier.</p>
    </div>
</body>
</html>

<h1 style="color: #e74c3c; text-align: left; margin-bottom: 50px;">3 - Vizualisation</h1>
<h3 style="color: #e74c3c; text-align: left;">1 - Répartition des variables</h3>
<h2 style="text-align: center; margin-top: 20px; color: #3498db;">A - Redécouverte du DataFrame</h2>

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [12]:
file_path = '../CSV/données_foncières_france_2024.csv'
df = pd.read_csv(file_path, low_memory=False)

In [13]:
df.head()

,id_mutation,date_mutation,numero_disposition,nature_mutation,adresse_numero,adresse_nom_voie,nom_commune,code_departement,lot1_numero,lot1_surface_carrez,...,lot5_surface_carrez,type_local,surface_reelle_bati,surface_terrain,nombre_pieces_principales,nature_culture,nature_culture_speciale,longitude,latitude,valeur_fonciere
0,2024-1,2024-01-02,1,Vente,NaN,LE DELIVRE,Chaley,1.0,NaN,NaN,...,NaN,NaN,NaN,99.0,NaN,prés,NaN,5.530952,45.952439,346.5
1,2024-2,2024-01-03,2,Vente,NaN,CHEVRY DESSOUS,Chevry,1.0,NaN,NaN,...,NaN,NaN,NaN,115.0,NaN,sols,NaN,6.043339,46.282256,10000.0
2,2024-3,2024-01-08,1,Vente,NaN,PIN HAMEAU,Laiz,1.0,NaN,NaN,...,NaN,NaN,NaN,497.0,NaN,sols,NaN,4.911143,46.247235,249000.0
3,2024-4,2024-01-03,1,Vente,29.0,PL DU JURA,Gex,1.0,175,NaN,...,NaN,Dépendance,NaN,NaN,0.0,NaN,NaN,6.058695,46.332212,329500.0
4,2024-4,2024-01-03,1,Vente,29.0,PL DU JURA,Gex,1.0,175,NaN,...,NaN,Dépendance,NaN,NaN,0.0,NaN,NaN,6.058695,46.332212,329500.0

Comprendre a quel type de data frame nous allons devoiur traité (tailles, variables)

In [14]:
df.shape

(1504616, 27)

<h2 style="text-align: center; color: #3498db;">B - Affichage de la répartition des variables pertinentes sur le dataset complet</h2>

In [15]:
def afficher_repartition_categorique(df, colonne_nom):
    plt.figure(figsize=(17, 6))
    sns.countplot(x=df[colonne_nom], hue=df[colonne_nom], palette='Blues_d')
    plt.title(f'Repartition des mutations par {colonne_nom}')  
    plt.xlabel(colonne_nom)  
    plt.ylabel('Nombre de mutations')  
    plt.xticks(rotation=60)
    plt.tight_layout()
    plt.show()

In [16]:
def afficher_repartition_numerique(df, colonne_nom):
    plt.figure(figsize=(17, 5))
    sns.kdeplot(df[colonne_nom], fill=True, color='skyblue')
    plt.title(f'{colonne_nom} Distribution')  
    plt.xlabel(colonne_nom)  
    plt.ylabel('Probability')
    plt.tight_layout()
    plt.show()

<h1 style="margin-top: 100px;">1 - Distribution des dates auxquelles ont été réalisées les transactions</h1>